<?php
if (!defined('FREEPBX_IS_AUTH')) { die('No direct script access allowed'); }
//take a copy of existing amd.conf
//lets read the existing configuration
$dir = \FreePBX::Config()->get('ASTETCDIR');
$existingdata = array();
if(file_exists($dir.'/amd.conf') && !file_exists($dir.'/amd.conf.backup')) {
	$contents = file_get_contents($dir.'/amd.conf');
	if(strpos($contents,"Do NOT edit this file as it is auto-generated") === false) {
		out(_("amd.conf Configuration file found"));
		$lines = parse_ini_string($contents,INI_SCANNER_RAW);
		if(isset($lines['general'])) {
			$existingdata = $lines['general'];
		}
		rename($dir.'/amd.conf',$dir.'/amd.conf.backup');
	}
}
if(!empty($existingdata)) {
	FreePBX::AMD()->addAmdSettings($existingdata);
	out(_("Restoring the existing settings"));
} else {
	$data_value = FreePBX::AMD()->getAmdSettings();
	if(empty($data_value)){
		$data = array(
			"initial_silence" => 2500,
			"greeting" => 1500,
			"after_greeting_silence" => 800,
			"total_analysis_time" => 5000,
			"min_word_length" => 100,
			"maximum_word_length" => 5000,
			"between_words_silence" => 50,
			"maximum_number_of_words" => 3,
			"silence_threshold" => 256
		);
		FreePBX::AMD()->addAmdSettings($data);
	}
}
